GET  http://localhost:8080

// login
###
POST http://localhost:8080/user/login
Content-Type: application/json

{
    "gmail": "dimas@gmail.com",
    "password": "dimas1122"
}

// dashboard
###w
GET http://localhost:8080/dashboard


// register
###
POST http://localhost:8080/user/register
Content-Type: application/json

{
    "name": "dimas",
    "gmail": "dimas@gmail.com",
    "password": "dimas1122"
}

// logout
### 
DELETE http://localhost:8080/user/logout